defaults:
  - default
  - _self_
## library_id
### For group, can be found in the URL to your library https://www.zotero.org/groups/4932032/zendron
### For user, can be found https://www.zotero.org/settings/keys
library_id : 4932332 # STARTER CONFIG
library_type : group # group or user # STARTER CONFIG
api_key : FoC1uOvsMnNdYmpYuY5JpETw # STARTER CONFIG
## collection
### null for entire library - exact match to unique collection
collection: null 
local_image_path: /Users/<username>/Zotero/cache # STARTER CONFIG
